backend:
  name: github
  repo: invmv/astroverse
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://invmy.us.kg
  auth_endpoint: /api/auth
media_folder: pubilc/uploads
public_folder: uploads
collections:
  - name: "Home"
    label: "Home"
    folder: "src/content/posts"
    slug: "{{title | slugify}}"  # 自动生成的文件名格式
    summary: "{{pubDate}} {{title}}"
    create: true
    fields:
      - { label: "author", name: "author", widget: "string", default: "invmy", hidden: true }
      - { label: "封面图片", name: "cover", widget: "image", hint: "只允许使用URL插入，不允许上传"}
      - { label: "封面描述", name: "coverAlt", widget: "string"}
      - { label: "标题", name: "title", widget: "string" }
      - { label: "描述", name: "description", widget: "text" }
      - { label: "发布日期", name: "pubDate", widget: "datetime", format: "YYYY-MM-DD" }
      
      # 分类字段，用户可以从预定义分类中选择
      - label: "分类"
        name: "category"
        widget: "list"
        allow_add: false
        options:
          - label: "review"
            value: "review"
          - label: "mytrade"
            value: "mytrade"
          - label: "other"
            value: "other"
      
      # 标签字段，用户可以自由添加多个标签
      - label: "标签"
        name: "tags"
        widget: "list"
        allow_add: true
        hint: "标签使用英文逗号+空格隔开，如标签1, 标签2, 标签3"
      
      - name: "body"
        label: "正文"
        widget: "markdown"
        modes: ["raw", "rich_text"]
